# tensors

following along with [this page](https://www.tensorflow.org/programmers_guide/tensors)

you'd never guess it from the name, but `tensorflow` cares about objects called *tensors*. internally, tensors are multi-dimensional arrays of a shared `dtype`. conceptually, they represent "partially d efined computation", and are fully defined by their relationships to other tensors (I imagine this was originally a contraction operation on some indices; perhaps internally everything is still represented this way)

In [12]:
import tensorflow as tf

import utils

each tensor has a *data type* and a *shape*. the datatype is known and requrieed and constant across all values within a tensor. the shape is not necessarily known ahead of time.

they enumerate some of the basic tensor types:

+ `tf.Variable`
+ `tf.constant`
+ `tf.placeholder`
+ `tf.SparseTensor`

## rank

each tensor has a shape; `rank` is defined as the number of independent dimensions in that shape. also called *order* or *degree* or *n-dimension*. this is not the matrix rank (the dimensionality of the kernel)

### rank 0

each of the following are rank 0 (i.e. a scalar)

In [3]:
mammal = tf.Variable("Elephant", tf.string)
ignition = tf.Variable(451, tf.int16)
floating = tf.Variable(3.14159265359, tf.float64)
its_complicated = tf.Variable(12.3 - 4.85j, tf.complex64)

### rank 1

the following are rank 1 (i.e. vectors). syntactically, the only difference is the surrounding variables, and possibly the number of provided elements

In [4]:
mystr = tf.Variable(["Hello"], tf.string)
cool_numbers  = tf.Variable([3.14159, 2.71828], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([12.3 - 4.85j, 7.5 - 6.23j], tf.complex64)

### higher ranks

rank 2:

In [30]:
mymat = tf.Variable([[7],[11]], tf.int16)
myxor = tf.Variable([[False, True],[True, False]], tf.bool)
linear_squares = tf.Variable([[4], [9], [16], [25]], tf.int32)
squarish_squares = tf.Variable([ [4, 9], [16, 25] ], tf.int32)
rank_of_squares = tf.rank(squarish_squares)
mymatC = tf.Variable([[7],[11]], tf.int32)

rank 4:

In [8]:
my_image = tf.zeros(
    shape=[
        10,  # batch size
        299,  # image height
        299,  # image width
        3  # rgb color channels
    ]
)

### getting a `tf.Tensor` object's rank

shit ain't hard folks

In [9]:
tf.rank(my_image)

<tf.Tensor 'Rank_1:0' shape=() dtype=int32>

In [25]:
utils.inspect(tf.rank(my_image))

4


### referring to `tf.Tensor` slices

to access any one element in an $n$ dimension tensor you must specify $n$ indices. you are allowed to use slicing with the `:` character

In [32]:
squarish_squares = tf.Variable(
    initial_value=[
        [4, 9],
        [16, 25]
    ], 
    dtype=tf.int32
)
utils.inspect(squarish_squares[:, 0], init_global=True)

[ 4 16]


## shape

the *shape* of the tensor is the number of elements in the tensor in each dimension. the shape may or may not be known (it is *only* known if the rank is known; if the rank is not known the shape is definitely unknown).

### getting a `tf.Tensor` object's shape

it's `tf.Tensor.shape`:

In [40]:
squarish_squares.shape

TensorShape([Dimension(2), Dimension(2)])

### changing the shape of a `tf.Tensor`

if you know you need a tensor in a new shape, you'll never guess what you do!

`tf.reshape`:

In [45]:
rank_three_tensor = tf.ones([3, 4, 5])
rank_three_tensor

<tf.Tensor 'ones_1:0' shape=(3, 4, 5) dtype=float32>

In [46]:
utils.inspect(rank_three_tensor)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


we have $3 \times 4 \times 5 = 60$ elements, so we have to have that many elements in our reshaped tensor (right? or can it be padded somehow?)

In [49]:
matrix = tf.reshape(
    tensor=rank_three_tensor,
    shape=[6, 10]
)
matrix

<tf.Tensor 'Reshape_2:0' shape=(6, 10) dtype=float32>

In [50]:
utils.inspect(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


we can provide a `-1` to any one of the new shapes to request `tensorflow` calculate the dimension size for us. for example, here we specify one dimension of size 3 and the other of size whatever (whatever is 20, here):

In [51]:
matrixB = tf.reshape(matrix, [3, -1])
matrixB

<tf.Tensor 'Reshape_3:0' shape=(3, 20) dtype=float32>

In [52]:
utils.inspect(matrixB)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


similarly with higher rank tensor:

In [53]:
matrixAlt = tf.reshape(matrixB, [4, 3, -1])
matrixAlt

<tf.Tensor 'Reshape_4:0' shape=(4, 3, 5) dtype=float32>

In [54]:
utils.inspect(matrixAlt)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


Note that the number of elements of the reshaped Tensors has to match the original number of elements. Therefore, the following example generates an error because no possible value for the last dimension will match the number of elements.

In [59]:
try:
    yet_another = tf.reshape(matrixAlt, [13, 2, -1])
except (tf.errors.InvalidArgumentError, ValueError) as e:
    print("told ya there'd be an error")
    print('error: {}'.format(e))

told ya there'd be an error
error: Dimension size must be evenly divisible by 26 but is 60 for 'Reshape_9' (op: 'Reshape') with input shapes: [4,3,5], [3] and with input tensors computed as partial shapes: input[1] = [13,2,?].


## data types

only one type, but they suggest you can serialize arbitrary data types as strings and use a base string type. this seems like bad advice, gang

In [64]:
matrix.dtype

tf.float32

## evaluating tensors

each tensor has a `tf.Tensor.eval` method hich can be used to evaluate it within a running session. note that this is *not* an opeation, so it's not something that could be executed with `sess.run` (as is done in `utils.inspect`); rather you can just call it straight away within a session context

In [95]:
constant = tf.constant([1, 2, 3])
tensor = constant * constant

with tf.Session() as sess:
    print(tensor.eval())

[1 4 9]


the authors then remind us placeholders exist and need `feed_dict` dictionaries to operate (this has been discussed before only in the context of sessions, so it *is* new to suggest they are required for `tf.Tensor.eval` calls)

In [96]:
p = tf.placeholder(tf.float32)
t = p + 1.0

In [97]:
with tf.Session() as sess:
    try:
        print(t.eval())
    except (tf.errors.InvalidArgumentError, ValueError) as e:
        print("told ya there'd be an error")
        print('error: {}...'.format(str(e)[:200]))

told ya there'd be an error
error: You must feed a value for placeholder tensor 'Placeholder_1' with dtype float
	 [[Node: Placeholder_1 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU...


In [98]:
with tf.Session() as sess:
    print(t.eval(feed_dict={p: 2.0}))

3.0


## printing tensors

for advanced debugging you should use `tfdbg` (their suggestion), but for simple shit you can print using `tf.Print`.

note that the regular `print` function is helpful only to a point, printing the class `repr` for the `tf.Tensor` class / subclass

In [99]:
print(t)

Tensor("add_6:0", dtype=float32)


it looks, to me, that `tf.Print` is a decorator of sorts, which wraps a tensor and then prints the result after evaluation:

In [100]:
t = tf.Print(t, [t])
t

<tf.Tensor 'Print_5:0' shape=<unknown> dtype=float32>

In [101]:
result = t + 1

In [103]:
with tf.Session() as sess:
    result = t + 1
    print(result.eval(feed_dict={p: 2.0}))

4.0


okay, well, that didn't work. I wonder if `tf.Print` is debugging to a lower debug level than `jupyter` is supporting by default...

nope, looks like it prints to `stderr`. only available in the `jupyter` notebook service's logs. says directly in the `tf.Print` docs that this is not compatible with `jupyter` notebooks (no idea why they don't mention this is the web docs, but whatever).

oh well

# summary

this was a very simple overview of tensors

1. they have shape, dimension, and rank, kind of
1. they have one and only one datatype
1. they have a `tf.Tensor.eval` method
1. they can be print (to stderr, so terminal only) by an identity operation `tf.Print`